class semcourses {
  static Map<dynamic, Map<dynamic, List<dynamic>>> Courses = {
    1: {
      'core': [
        'Mathematics-1',
        'Physics-1 ',
        'Software Development Fundamentals-I',
        'English',
        'Physics Lab-1',
        'Software Development Lab-I ',
        'Engineering Drawing & Design'
      ],
      'elective': []
    },
    2: {
      'core': [
        'Mathematics-2',
        'Physics-2 ',
        'Electrical Science-I',
        'Software Development FundamentalsII',
        'Physics Lab-2',
        'Electrical Science Lab-I',
        'Software Development Lab-II',
        'Workshop '
      ],
      'elective': []
    },
    3: {
      'core': [
        'Theoretical Foundations of Computer Science',
        'Database Systems and Web ',
        'Data Structures ',
        'Data Structures Lab',
        'Database Systems and Web Lab ',
        'Electrical Science-II',
        'Electrical Science Lab-II',
        'Economics '
      ],
      'elective': []
    },
    4: {
      'core': [
        'Probability and Random Processes',
        'Digital Systems',
        'Algorithms and Problem Solving',
        'Environmental Science',
        'Life Skills'
      ],
      'elective': []
    },
    5: {
      'core': [
        'Computer Organisation and Architecture',
        'Operating Systems and Systems Programming',
        'Information Security Lab',
        'Indian Constitution and Traditional Knowledge'
      ],
      'elective': [
        'Fundamentals of Machine learning',
        'Fundamentals of Computer security',
        'Introduction to Big data and Data Analytics',
        'Object Oriented Analysis and Design using Java',
        'Image Processing and Computer Vision',
        'Automata Theory and its applications',
      ]
    },
    6: {
      'core': [
        'Computer Networks and Internet of Things',
        'Software Engineering',
        'Artificial Intelligence',
      ],
      'elective': [
        'Sensor Technology & Android Programming',
        'Fundamentals of Distributed and Cloud Computing',
        'Introduction to Large Scale Database Systems',
        'Web Technology and Cyber Security',
        'Introduction to Compiler Design',
        'Cloud based Enterprise Systems',
      ]
    },
    7: {
      'core': [],
      'elective': [
        'Advanced Blockchain',
        'Big Data with Hadoop and Spark',
        'Introduction to Deep Learning',
        'Cryptography and its Applications',
        'Information Retrieval and Semantic Web',
        'IoT Analytics',
      ]
    },
    8: {
      'core': [],
      'elective': [
        'Optimization Techniques',
        'Artificial Intelligence for Healthcare',
        'Cloud Computing Essentials',
        'Agile',
        'Kubernetes',
        'International Studies'
      ]
    },
  };
  static List<int> percentage = [
    80,
    57,
    61,
    79,
    51,
    67,
    73,
    68,
    47,
    69,
    68,
    57,
    59,
    70,
    54,
    64,
    90,
    93,
    86,
    54,
    84,
    55,
    89,
    59,
    41,
    97,
    73,
    64,
    84,
    74,
    41,
    52,
    47,
    76,
    73,
    60,
    55,
    75,
    68,
    73,
    77,
    59,
    90,
    45,
    97,
    67,
    76,
    86,
    50,
    81,
    88,
    69,
    95,
    84,
    67,
    60,
    98,
    78,
    95,
    49,
    55,
    79,
    70,
    81,
    50,
    71,
    92,
    57,
    88,
    64,
    61,
    92,
    91,
    62,
    59,
    94,
    80,
    58,
    57,
    67,
    49,
    91,
    73,
    89,
    60,
    71,
    62,
    66,
    58,
    81,
    95,
    83,
  ];
}
