// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoypEv-rrXg7ljjCHXqdA8VTKH5ogPCvw',
    appId: '1:932337002065:web:06bae7c37fb3666d5eba70',
    messagingSenderId: '932337002065',
    projectId: 'codingbytes-2066e',
    authDomain: 'codingbytes-2066e.firebaseapp.com',
    storageBucket: 'codingbytes-2066e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZC92EP1W_uwGl4gsMoREZWsTQ6fVec4',
    appId: '1:932337002065:android:5ec10259d2811fa85eba70',
    messagingSenderId: '932337002065',
    projectId: 'codingbytes-2066e',
    storageBucket: 'codingbytes-2066e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9XUQL88nax927gdcE5CLeWkPB8ANLDD8',
    appId: '1:932337002065:ios:fab5ba80cc07b5b45eba70',
    messagingSenderId: '932337002065',
    projectId: 'codingbytes-2066e',
    storageBucket: 'codingbytes-2066e.appspot.com',
    iosClientId: '932337002065-9fcebp99j7jdpnmeu2psknqb0olslbku.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeBytes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9XUQL88nax927gdcE5CLeWkPB8ANLDD8',
    appId: '1:932337002065:ios:fab5ba80cc07b5b45eba70',
    messagingSenderId: '932337002065',
    projectId: 'codingbytes-2066e',
    storageBucket: 'codingbytes-2066e.appspot.com',
    iosClientId: '932337002065-9fcebp99j7jdpnmeu2psknqb0olslbku.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeBytes',
  );
}
